env:
  browser: true
  es6: true
  jest: true
plugins:
  - jest
  - import
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2022
  sourceType: module
rules:
  spaced-comment: off
