x-volumes: &default-volumes
  volumes:
    - ./dist:/app/dist

services:
  compile:
    build: .
    image: statuspage-embed
    entrypoint: ["npm", "run", "build"]
    #<<: *default-volumes

  dev:
    build:
      dockerfile: Dockerfile.development
    image: statuspage-embed
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    #<<: *default-volumes

  test:
    build: .
    image: statuspage-embed
    command:
      - /bin/sh
      - -c
      - |
        npm run test
