x-volumes: &default-volumes
  volumes:
    - ./dist:/app/dist
    - ./js:/app/js
    - ./public:/app/public
    - ./test/unit:/app/test/unit

services:
  compile:
    build: .
    image: statuspage-embed
    entrypoint: ["npm", "run", "build"]
    #<<: *default-volumes

  dev:
    build:
      dockerfile: Dockerfile.development
    image: statuspage-embed
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    # See the note about HMR not picking up changes to source files made in the
    # hypervisor in the "Develop" section of README.md.
    #<<: *default-volumes

  statuspage-proxy:
    build:
      dockerfile: Dockerfile.statuspage-proxy
    environment:
      - API_KEY=${API_KEY}
      - STATUSPAGE_URL=${STATUSPAGE_URL}
    image: statuspage-summary-cors-proxy
    ports:
      - "3000:3000"
    #<<: *default-volumes

  test:
    build: .
    image: statuspage-embed
    command: ["npm", "run", "test"]
    #<<: *default-volumes

  test-watch:
    build: .
    image: statuspage-embed
    command: ["npm", "run", "test:watch"]
    #<<: *default-volumes
