FROM node:24.15.0-trixie

ENV INSTALL_PATH /app

COPY package.json $INSTALL_PATH
COPY src/js/config.mjs $INSTALL_PATH/src/js/
COPY tools $INSTALL_PATH/tools

WORKDIR $INSTALL_PATH

CMD ["npm", "run", "statuspage-proxy"]

