FROM node:24.15.0-trixie

WORKDIR /app

COPY public/ ./public
COPY src/ ./src
COPY index.html .
COPY package.json .
COPY package-lock.json .
COPY vite.config.js .

RUN npm install

EXPOSE 5173

CMD ["npm", "run", "dev"]
