import { fileURLToPath } from 'node:url';

import { includeIgnoreFile } from '@eslint/compat';
import { defineConfig, globalIgnores } from 'eslint/config';
import js from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';
import globals from 'globals';

// "The AudioWorkletGlobalScope property in globals.browser breaks ESLint #239"
// https://github.com/sindresorhus/globals/issues/239
const globalsBrowserFixed = {
    ...globals.browser,
    AudioWorkletGlobalScope: false, // this is the default,
};
delete globalsBrowserFixed[ 'AudioWorkletGlobalScope ' ];

const gitignorePath = fileURLToPath( new URL( '.gitignore', import.meta.url ) );

export default defineConfig( [
    includeIgnoreFile( gitignorePath, 'Imported .gitignore patterns' ),
    globalIgnores( [ 'browser-overrides/**' ] ),

    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType : 'module',

            globals: {
                ...globalsBrowserFixed,
                ...globals.node,
            },
        },

        plugins: {
            '@stylistic': stylistic,
        },

        rules: {
            /* eslint-disable @stylistic/max-len, vue/max-len */

            // Generated by `npm init quasar@latest` when making the eslint
            // config file in another project.  They look useful.
            'prefer-promise-reject-errors': 'off',
            // Allow debugger during development only
            'no-debugger'                 : process.env.NODE_ENV === 'production' ? 'error' : 'off',

            '@stylistic/array-bracket-newline'    : [ 'error', 'consistent' ],
            '@stylistic/array-bracket-spacing'    : [ 'error', 'always' ],
            '@stylistic/array-element-newline'    : [ 'error', 'consistent' ],
            '@stylistic/arrow-spacing'            : [ 'error', { 'before': true, 'after': true } ],
            '@stylistic/block-spacing'            : [ 'error', 'always' ],
            '@stylistic/brace-style'              : [ 'error', '1tbs' ],
            '@stylistic/comma-dangle'             : [ 'error', 'always-multiline' ],
            '@stylistic/comma-spacing'            : [ 'error', { 'before': false, 'after': true } ],
            '@stylistic/comma-style'              : [ 'error', 'last' ],
            '@stylistic/computed-property-spacing': [ 'error', 'always' ],
            '@stylistic/dot-location'             : [ 'error', 'property' ],
            '@stylistic/function-call-spacing'    : [ 'error', 'never' ],
            '@stylistic/indent'                   : [ 'error', 4 ],
            '@stylistic/key-spacing'              : [ 'error', { align: 'colon' } ],
            '@stylistic/keyword-spacing'          : [ 'error', { before: true } ],
            '@stylistic/max-len'                  : [ 'warn', { code: 80, tabWidth: 4 } ],
            '@stylistic/multiline-ternary'        : [ 'error', 'always-multiline' ],
            '@stylistic/no-extra-parens'          : [ 'error', 'all' ],
            '@stylistic/object-curly-newline'     : [ 'error', { multiline: true, consistent: true } ],
            '@stylistic/object-curly-spacing'     : [ 'error', 'always' ],
            '@stylistic/object-property-newline'  : [ 'error', { allowAllPropertiesOnSameLine: true } ],
            '@stylistic/operator-linebreak'       : [ 'error', 'after' ],
            '@stylistic/quotes'                   : [ 'error', 'single' ],
            '@stylistic/semi'                     : [ 'error', 'always' ],
            '@stylistic/space-in-parens'          : [ 'error', 'always' ],
            '@stylistic/space-infix-ops'          : [ 'error' ],
            '@stylistic/space-unary-ops'          : [ 'error', { words: true, nonwords: false } ],
            '@stylistic/template-curly-spacing'   : [ 'error', 'always' ],

            /* eslint-enable @stylistic/max-len, vue/max-len */
        },
    },
] );
