docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.3-dc-1.24.1-0
  working_directory: ~/app

docker_build: &docker_build
  run:
    name: Docker build
    command: |
      docker-compose build test compile

test: &test
  run:
    name: Test
    command: |
      docker-compose run test

webpack_compile: &webpack_compile
  run:
    name: Webpack compile
    command: |
      docker-compose run compile

webpack_copy: &webpack_copy
  run:
    name: Copy Webpack build
    command: |
      docker cp $(docker ps -a -q --filter name=compile):/app/dist ./

aws_env: &aws_env
  run:
    name: Export AWS env vars
    command: |
      echo 'export AWS_ACCESS_KEY_ID=${WEB_CDN_AWS_ACCESS_KEY_ID}' >> $BASH_ENV
      echo 'export AWS_SECRET_ACCESS_KEY=${WEB_CDN_AWS_SECRET_ACCESS_KEY}' >> $BASH_ENV

s3_deploy: &s3_deploy
  aws-s3/sync:
    from: dist
    to: '${S3_URI}/statuspage-embed'
    arguments: |
      --delete
    overwrite: true

version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  deploy_dev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Export Dev environment
          command: |
            echo 'export DEPLOY_ENV=dev' >> $BASH_ENV
      - *docker_build
      - *test
      - *webpack_compile
      - *webpack_copy
      - *aws_env
      - *s3_deploy

  deploy_prod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Export Dev environment
          command: |
            echo 'export DEPLOY_ENV=prod' >> $BASH_ENV
      - *docker_build
      - *test
      - *webpack_compile
      - *webpack_copy
      - *aws_env
      - *s3_deploy

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - deploy_dev:
          context: web-cdn-aws-nyulitsdev
          filters:
            branches:
              ignore:
                - master
      - deploy_prod:
          context: web-cdn-aws-nyulits
          filters:
            branches:
              only: master
