machine-defaults: &machine-defaults
  machine:
    image: ubuntu-2204:current
  working_directory: ~/app

docker_build: &docker_build
  run:
    name: Docker build
    command: |
      docker compose build test compile

test: &test
  run:
    name: Test
    command: |
      docker compose run test

webpack_copy: &webpack_copy
  run:
    name: Copy Webpack build
    command: |
      docker cp $(docker ps -a -q --filter name=compile):/app/dist ./

webpack_test: &webpack_test
  run:
    name: Test that webpack built correct files
    command: |
      test -e dist/index.min.css
      test -e dist/index.min.js

aws_env: &aws_env
  run:
    name: Export AWS env vars
    command: |
      echo 'export AWS_ACCESS_KEY_ID=${WEB_CDN_AWS_ACCESS_KEY_ID}' >> $BASH_ENV
      echo 'export AWS_SECRET_ACCESS_KEY=${WEB_CDN_AWS_SECRET_ACCESS_KEY}' >> $BASH_ENV

# Note that `aws s3 sync ... --exact-timestamps` only works for downloads from S3,
# not uploads: https://github.com/aws/aws-cli/issues/4460.  The only safe way
# to update is to upload absolutely everything using `cp` and then deleting
# removed files using `sync --delete`.  There are many other open GitHub issues
# related to this behavior.  Here's another: https://github.com/aws/aws-cli/issues/3273
aws-sync-s3: &aws-sync-s3
  run:
    name: Deploy to S3
    command: |
      aws s3 cp --recursive dist ${S3_URI}/statuspage-embed && \
      aws s3 sync --delete dist ${S3_URI}/statuspage-embed

version: 2.1
jobs:
  deploy_dev:
    <<: *machine-defaults
    steps:
      - checkout
      - *docker_build
      - *test
      - run:
          name: Webpack compile stage
          command: |
            docker compose run compile build:stage
      - *webpack_copy
      - *webpack_test
      - *aws_env
      - *aws-sync-s3

  deploy_prod:
    <<: *machine-defaults
    steps:
      - checkout
      - *docker_build
      - *test
      - run:
          name: Webpack compile prod 
          command: |
            docker compose run compile build:prod
      - *webpack_copy
      - *webpack_test
      - *aws_env
      - *aws-sync-s3

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - deploy_dev:
          context: web-cdn-aws-nyulitsdev
          filters:
            branches:
              ignore:
                - master
      - deploy_prod:
          context: web-cdn-aws-nyulits
          filters:
            branches:
              only: master
